# Main Bindplane Container App
apiVersion: apps/v1
kind: ContainerApp
metadata:
  name: bindplane
  namespace: default
spec:
  environmentId: {{.ACAEnvironmentID}}
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: false
      targetPort: 3001
  template:
    containers:
      - name: server
        image: ghcr.io/observiq/bindplane-ee:1.94.0
        resources:
          cpu: 2000m
          memory: 8192Mi
        env:
          - name: KUBERNETES_NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_CONTAINER_NAME
            value: "server"
          - name: BINDPLANE_MODE
            value: node
          - name: BINDPLANE_ANALYTICS_DISABLED
            value: "false"
          - name: BINDPLANE_TRANSFORM_AGENT_ENABLE_REMOTE
            value: "true"
          - name: BINDPLANE_TRANSFORM_AGENT_REMOTE_AGENTS
            value: "bindplane-transform-agent:4568"
          - name: BINDPLANE_LICENSE
            valueFrom:
              secretKeyRef:
                name: bindplane-license
                key: license
          - name: BINDPLANE_ACCEPT_EULA
            value: "true"
          - name: BINDPLANE_AGENT_VERSIONS_CLIENTS
            value: "github"
          - name: BINDPLANE_REMOTE_URL
            value: http://bindplane.local:80
          - name: BINDPLANE_WEB_URL
            value: http://bindplane.local:80
          - name: BINDPLANE_USERNAME
            value: bpuser
          - name: BINDPLANE_PASSWORD
            value: bppass
          - name: BINDPLANE_SESSION_SECRET
            value: 4484766F-5016-4077-B8E0-0DE1D637854B
          - name: BINDPLANE_LOGGING_OUTPUT
            value: stdout
          - name: BINDPLANE_CONFIG_HOME
            value: /data
          - name: BINDPLANE_STORE_TYPE
            value: postgres
          - name: BINDPLANE_POSTGRES_HOST
            value: {{.PostgresHost}}
          - name: BINDPLANE_POSTGRES_PORT
            value: "5432"
          - name: BINDPLANE_POSTGRES_USERNAME
            value: {{.PostgresUsername}}
          - name: BINDPLANE_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: BINDPLANE_POSTGRES_DATABASE
            value: {{.PostgresDatabase}}
          - name: BINDPLANE_POSTGRES_SSL_MODE
            value: disable
          - name: BINDPLANE_POSTGRES_SSL_ROOT_CERT
            value: /postgres-tls/ca.crt
          - name: BINDPLANE_POSTGRES_SSL_CERT
            value: /postgres-tls/client.crt
          - name: BINDPLANE_POSTGRES_SSL_KEY
            value: /postgres-tls/client.key
          - name: BINDPLANE_POSTGRES_MAX_CONNECTIONS
            value: "20"
          - name: BINDPLANE_EVENT_BUS_TYPE
            value: nats
          - name: BINDPLANE_NATS_CLIENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: BINDPLANE_NATS_CLIENT_ENDPOINT
            value: nats://bindplane-nats:4222
          - name: BINDPLANE_NATS_CLIENT_SUBJECT
            value: bindplane-event-bus
          - name: BINDPLANE_PORT
            value: "3001"
          - name: BINDPLANE_PROMETHEUS_ENABLE
            value: "true"
          - name: BINDPLANE_PROMETHEUS_ENABLE_REMOTE
            value: "true"
          - name: BINDPLANE_PROMETHEUS_HOST
            value: bindplane-prometheus
          - name: BINDPLANE_PROMETHEUS_PORT
            value: "9090"
          - name: BINDPLANE_PROMETHEUS_REMOTE_WRITE_ENDPOINT
            value: /api/v1/write
          - name: BINDPLANE_PROMETHEUS_AUTH_TYPE
            value: none
          - name: BINDPLANE_METRICS_TYPE
            value: prometheus
          - name: BINDPLANE_METRICS_PROMETHEUS_ENDPOINT
            value: /metrics
          - name: BINDPLANE_LOGGING_LEVEL
            value: debug
        ports:
          - containerPort: 3001
            name: http
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 0
          periodSeconds: 30
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
    scale:
      minReplicas: 1
      maxReplicas: 3
