# Secrets for the Container Apps
apiVersion: v1
kind: Secret
metadata:
  name: bindplane-license
  namespace: default
type: Opaque
data:
  license: {{.Base64License}}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  password: {{.Base64PostgresPassword}}

---
# Storage for persistent data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 120Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-storage-secret
    shareName: prometheus-data
    readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nats-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-storage-secret
    shareName: nats-data
    readOnly: false

---
# Azure Storage Account Secret (placeholder)
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: default
type: Opaque
data:
  azurestorageaccountname: {{.Base64StorageAccountName}}
  azurestorageaccountkey: {{.Base64StorageAccountKey}}
